export const SELECCIONAR_CLIENTE = 'SELECCIONAR_CLIENTE';
export const SELECCIONAR_PRODUCTO = 'SELECCIONAR_PRODUCTO';
export const CANTIDAD_PRODUCTOS = 'CANTIDAD_PRODUCTOS';
export const ACTUALIZAR_TOTAL = 'ACTUALIZAR_TOTAL';
export const SELECCIONAR_USUARIO = 'SELECCIONAR_USUARIO';
export const SELECCIONA_FECHA = 'SELECCIONA_FECHA';
export const SELECCIONA_HORA = 'SELCCIONA_HORA';

//Completar cita

export const SELECCION_PRODUCTO_COMPLETAR = 'SELECCION_PRODUCTO_COMPLETAR';
export const ACTUALIZAR_TOTAL_COMPLETAR = 'ACTUALIZAR_TOTAL_COMPLETAR';
export const SELECCIONAR_CUPON = 'SELECCIONAR_CUPON';